# coding: utf-8

"""
    Decision Service API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DecisionServiceConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'smart_plugin_configurations': 'list[SmartPluginConfiguration]',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'smart_plugin_configurations': 'smartPluginConfigurations',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, smart_plugin_configurations=None, timestamp=None):  # noqa: E501
        """DecisionServiceConfiguration - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._smart_plugin_configurations = None
        self._timestamp = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if smart_plugin_configurations is not None:
            self.smart_plugin_configurations = smart_plugin_configurations
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this DecisionServiceConfiguration.  # noqa: E501


        :return: The id of this DecisionServiceConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DecisionServiceConfiguration.


        :param id: The id of this DecisionServiceConfiguration.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def smart_plugin_configurations(self):
        """Gets the smart_plugin_configurations of this DecisionServiceConfiguration.  # noqa: E501


        :return: The smart_plugin_configurations of this DecisionServiceConfiguration.  # noqa: E501
        :rtype: list[SmartPluginConfiguration]
        """
        return self._smart_plugin_configurations

    @smart_plugin_configurations.setter
    def smart_plugin_configurations(self, smart_plugin_configurations):
        """Sets the smart_plugin_configurations of this DecisionServiceConfiguration.


        :param smart_plugin_configurations: The smart_plugin_configurations of this DecisionServiceConfiguration.  # noqa: E501
        :type: list[SmartPluginConfiguration]
        """

        self._smart_plugin_configurations = smart_plugin_configurations

    @property
    def timestamp(self):
        """Gets the timestamp of this DecisionServiceConfiguration.  # noqa: E501


        :return: The timestamp of this DecisionServiceConfiguration.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this DecisionServiceConfiguration.


        :param timestamp: The timestamp of this DecisionServiceConfiguration.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DecisionServiceConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecisionServiceConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
