# coding: utf-8

"""
    Decision Service API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SmartPluginConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plugin_name': 'str',
        'custom_plugin_selection': 'bool',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'plugin_name': 'pluginName',
        'custom_plugin_selection': 'customPluginSelection',
        'timestamp': 'timestamp'
    }

    def __init__(self, plugin_name=None, custom_plugin_selection=None, timestamp=None):  # noqa: E501
        """SmartPluginConfiguration - a model defined in Swagger"""  # noqa: E501
        self._plugin_name = None
        self._custom_plugin_selection = None
        self._timestamp = None
        self.discriminator = None
        if plugin_name is not None:
            self.plugin_name = plugin_name
        if custom_plugin_selection is not None:
            self.custom_plugin_selection = custom_plugin_selection
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def plugin_name(self):
        """Gets the plugin_name of this SmartPluginConfiguration.  # noqa: E501


        :return: The plugin_name of this SmartPluginConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._plugin_name

    @plugin_name.setter
    def plugin_name(self, plugin_name):
        """Sets the plugin_name of this SmartPluginConfiguration.


        :param plugin_name: The plugin_name of this SmartPluginConfiguration.  # noqa: E501
        :type: str
        """

        self._plugin_name = plugin_name

    @property
    def custom_plugin_selection(self):
        """Gets the custom_plugin_selection of this SmartPluginConfiguration.  # noqa: E501


        :return: The custom_plugin_selection of this SmartPluginConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._custom_plugin_selection

    @custom_plugin_selection.setter
    def custom_plugin_selection(self, custom_plugin_selection):
        """Sets the custom_plugin_selection of this SmartPluginConfiguration.


        :param custom_plugin_selection: The custom_plugin_selection of this SmartPluginConfiguration.  # noqa: E501
        :type: bool
        """

        self._custom_plugin_selection = custom_plugin_selection

    @property
    def timestamp(self):
        """Gets the timestamp of this SmartPluginConfiguration.  # noqa: E501


        :return: The timestamp of this SmartPluginConfiguration.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this SmartPluginConfiguration.


        :param timestamp: The timestamp of this SmartPluginConfiguration.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SmartPluginConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartPluginConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
