apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: smartem-decisions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: postgres-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: adminer-external
  namespace: smartem-decisions
spec:
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30808
  type: NodePort
