apiVersion: v1
kind: ConfigMap
metadata:
  name: smartem-config
  namespace: smartem-decisions
data:
  # These are fallback values used if ./tools/dev-k8s.sh is not used
  # The script will dynamically override these with values from .dev.env
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "smartem_db"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  HTTP_API_PORT: "8000"
  ADMINER_PORT: "8080"
  CORS_ALLOWED_ORIGINS: "*"
