apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: smartem-decisions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: smartem-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smartem-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: smartem_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: postgres-storage
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: smartem-decisions
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: smartem-decisions
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
  type: NodePort
