services:
  # RABBITMQ STUFF

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq

  # POSTGRES STUFF

  postgres:
    image: postgres:latest
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres/data/:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

  # GRAYLOG STUFF
  # Refs:
  # - https://www.virtualizationhowto.com/2023/09/graylog-docker-compose-setup-an-open-source-syslog-server-for-home-labs/

  mongodb:
    image: mongo:latest
    volumes:
      - ./volumes/mongodb/data:/data/db
#    networks:
#      - graylog-network
    restart: no

  # Ref: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
  # This creature arrived full of complaints so switching to elasticsearch
  #  opensearch:
  #    image: opensearchproject/opensearch:2
  #    environment:
  #      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
  #      - "bootstrap.memory_lock=true"
  #      - "discovery.type=single-node"
  #      - "action.auto_create_index=false"
  #      - "plugins.security.ssl.http.enabled=false"
  #      - "plugins.security.disabled=true"
  #      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=9f22CKX2gZo1$5"
  #    ulimits:
  #      memlock:
  #        hard: -1
  #        soft: -1
  #      nofile:
  #        soft: 65536
  #        hard: 65536
  #    ports:
  #      - "9200:9200"
  #      - "9600:9600"
  #    volumes:
  #      - ./volumes/opensearch/data:/usr/share/opensearch/data
  #    networks:
  #      - graylog-network
  #    restart: no

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: no
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      # Unlimited amount of memory set for elasticsearch container
      memlock:
        soft: -1
        hard: -1
    # Resource limit for elasticsearch set to 1 gigabyte
    mem_limit: 1g
    ports:
      - "9200:9200/tcp"
#    networks:
#      - graylog-network

  graylog:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.1.5}"
    depends_on:
      elasticsearch:
        condition: service_started
      mongodb:
        condition: service_started
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://localhost:9200"
      GRAYLOG_ELASTICSEARCH_VERSION: "7"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      - "${GRAYLOG_PORT}:10000/udp" # Custom UDP port
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - ./volumes/graylog/data:/usr/share/graylog/data/data
      - ./volumes/graylog/journal:/usr/share/graylog/data/journal
#    networks:
#      - graylog-network
    restart: no

#networks:
#  graylog-network:
#    driver: bridge
#    driver_opts:
#      # Ref: https://docs.docker.com/engine/network/drivers/bridge/#options
#      com.docker.network.bridge.enable_icc: "true"
