# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.engine_state import EngineState  # noqa: F401,E501
from swagger_server import util


class ApplicationStateChange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, state: EngineState=None, session_id: str=None, area_id: int=None, details: str=None):  # noqa: E501
        """ApplicationStateChange - a model defined in Swagger

        :param state: The state of this ApplicationStateChange.  # noqa: E501
        :type state: EngineState
        :param session_id: The session_id of this ApplicationStateChange.  # noqa: E501
        :type session_id: str
        :param area_id: The area_id of this ApplicationStateChange.  # noqa: E501
        :type area_id: int
        :param details: The details of this ApplicationStateChange.  # noqa: E501
        :type details: str
        """
        self.swagger_types = {
            'state': EngineState,
            'session_id': str,
            'area_id': int,
            'details': str
        }

        self.attribute_map = {
            'state': 'state',
            'session_id': 'sessionId',
            'area_id': 'areaId',
            'details': 'details'
        }
        self._state = state
        self._session_id = session_id
        self._area_id = area_id
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationStateChange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationStateChange of this ApplicationStateChange.  # noqa: E501
        :rtype: ApplicationStateChange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> EngineState:
        """Gets the state of this ApplicationStateChange.


        :return: The state of this ApplicationStateChange.
        :rtype: EngineState
        """
        return self._state

    @state.setter
    def state(self, state: EngineState):
        """Sets the state of this ApplicationStateChange.


        :param state: The state of this ApplicationStateChange.
        :type state: EngineState
        """

        self._state = state

    @property
    def session_id(self) -> str:
        """Gets the session_id of this ApplicationStateChange.


        :return: The session_id of this ApplicationStateChange.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this ApplicationStateChange.


        :param session_id: The session_id of this ApplicationStateChange.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def area_id(self) -> int:
        """Gets the area_id of this ApplicationStateChange.


        :return: The area_id of this ApplicationStateChange.
        :rtype: int
        """
        return self._area_id

    @area_id.setter
    def area_id(self, area_id: int):
        """Sets the area_id of this ApplicationStateChange.


        :param area_id: The area_id of this ApplicationStateChange.
        :type area_id: int
        """

        self._area_id = area_id

    @property
    def details(self) -> str:
        """Gets the details of this ApplicationStateChange.


        :return: The details of this ApplicationStateChange.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details: str):
        """Sets the details of this ApplicationStateChange.


        :param details: The details of this ApplicationStateChange.
        :type details: str
        """

        self._details = details
