# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acquisition_state import AcquisitionState  # noqa: F401,E501
from swagger_server import util


class AreaState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, session_id: str=None, area_id: int=None, state: AcquisitionState=None, timestamp: datetime=None):  # noqa: E501
        """AreaState - a model defined in Swagger

        :param id: The id of this AreaState.  # noqa: E501
        :type id: int
        :param session_id: The session_id of this AreaState.  # noqa: E501
        :type session_id: str
        :param area_id: The area_id of this AreaState.  # noqa: E501
        :type area_id: int
        :param state: The state of this AreaState.  # noqa: E501
        :type state: AcquisitionState
        :param timestamp: The timestamp of this AreaState.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'id': int,
            'session_id': str,
            'area_id': int,
            'state': AcquisitionState,
            'timestamp': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'session_id': 'sessionId',
            'area_id': 'areaId',
            'state': 'state',
            'timestamp': 'timestamp'
        }
        self._id = id
        self._session_id = session_id
        self._area_id = area_id
        self._state = state
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'AreaState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaState of this AreaState.  # noqa: E501
        :rtype: AreaState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this AreaState.


        :return: The id of this AreaState.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this AreaState.


        :param id: The id of this AreaState.
        :type id: int
        """

        self._id = id

    @property
    def session_id(self) -> str:
        """Gets the session_id of this AreaState.


        :return: The session_id of this AreaState.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this AreaState.


        :param session_id: The session_id of this AreaState.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def area_id(self) -> int:
        """Gets the area_id of this AreaState.


        :return: The area_id of this AreaState.
        :rtype: int
        """
        return self._area_id

    @area_id.setter
    def area_id(self, area_id: int):
        """Sets the area_id of this AreaState.


        :param area_id: The area_id of this AreaState.
        :type area_id: int
        """

        self._area_id = area_id

    @property
    def state(self) -> AcquisitionState:
        """Gets the state of this AreaState.


        :return: The state of this AreaState.
        :rtype: AcquisitionState
        """
        return self._state

    @state.setter
    def state(self, state: AcquisitionState):
        """Sets the state of this AreaState.


        :param state: The state of this AreaState.
        :type state: AcquisitionState
        """

        self._state = state

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this AreaState.


        :return: The timestamp of this AreaState.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this AreaState.


        :param timestamp: The timestamp of this AreaState.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
