# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.acquisition_state import AcquisitionState  # noqa: F401,E501
from swagger_server import util


class AreaStateChange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, area_id: int=None, state: AcquisitionState=None):  # noqa: E501
        """AreaStateChange - a model defined in Swagger

        :param session_id: The session_id of this AreaStateChange.  # noqa: E501
        :type session_id: str
        :param area_id: The area_id of this AreaStateChange.  # noqa: E501
        :type area_id: int
        :param state: The state of this AreaStateChange.  # noqa: E501
        :type state: AcquisitionState
        """
        self.swagger_types = {
            'session_id': str,
            'area_id': int,
            'state': AcquisitionState
        }

        self.attribute_map = {
            'session_id': 'sessionId',
            'area_id': 'areaId',
            'state': 'state'
        }
        self._session_id = session_id
        self._area_id = area_id
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'AreaStateChange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaStateChange of this AreaStateChange.  # noqa: E501
        :rtype: AreaStateChange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this AreaStateChange.


        :return: The session_id of this AreaStateChange.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this AreaStateChange.


        :param session_id: The session_id of this AreaStateChange.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def area_id(self) -> int:
        """Gets the area_id of this AreaStateChange.


        :return: The area_id of this AreaStateChange.
        :rtype: int
        """
        return self._area_id

    @area_id.setter
    def area_id(self, area_id: int):
        """Sets the area_id of this AreaStateChange.


        :param area_id: The area_id of this AreaStateChange.
        :type area_id: int
        """

        self._area_id = area_id

    @property
    def state(self) -> AcquisitionState:
        """Gets the state of this AreaStateChange.


        :return: The state of this AreaStateChange.
        :rtype: AcquisitionState
        """
        return self._state

    @state.setter
    def state(self, state: AcquisitionState):
        """Sets the state of this AreaStateChange.


        :param state: The state of this AreaStateChange.
        :type state: AcquisitionState
        """

        self._state = state
