# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AreaType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GRIDSQUARE = "gridsquare"
    FOILHOLE = "foilhole"
    ATLAS = "atlas"
    PARTICLE = "particle"
    def __init__(self):  # noqa: E501
        """AreaType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AreaType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AreaType of this AreaType.  # noqa: E501
        :rtype: AreaType
        """
        return util.deserialize_model(dikt, cls)
