# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RunStop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, run_number: int=None, reason: str=None):  # noqa: E501
        """RunStop - a model defined in Swagger

        :param session_id: The session_id of this RunStop.  # noqa: E501
        :type session_id: str
        :param run_number: The run_number of this RunStop.  # noqa: E501
        :type run_number: int
        :param reason: The reason of this RunStop.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'session_id': str,
            'run_number': int,
            'reason': str
        }

        self.attribute_map = {
            'session_id': 'sessionId',
            'run_number': 'runNumber',
            'reason': 'reason'
        }
        self._session_id = session_id
        self._run_number = run_number
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'RunStop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunStop of this RunStop.  # noqa: E501
        :rtype: RunStop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this RunStop.


        :return: The session_id of this RunStop.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this RunStop.


        :param session_id: The session_id of this RunStop.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def run_number(self) -> int:
        """Gets the run_number of this RunStop.


        :return: The run_number of this RunStop.
        :rtype: int
        """
        return self._run_number

    @run_number.setter
    def run_number(self, run_number: int):
        """Sets the run_number of this RunStop.


        :param run_number: The run_number of this RunStop.
        :type run_number: int
        """

        self._run_number = run_number

    @property
    def reason(self) -> str:
        """Gets the reason of this RunStop.


        :return: The reason of this RunStop.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this RunStop.


        :param reason: The reason of this RunStop.
        :type reason: str
        """

        self._reason = reason
