# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RunStart(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None):  # noqa: E501
        """RunStart - a model defined in Swagger

        :param session_id: The session_id of this RunStart.  # noqa: E501
        :type session_id: str
        """
        self.swagger_types = {
            'session_id': str
        }

        self.attribute_map = {
            'session_id': 'sessionId'
        }
        self._session_id = session_id

    @classmethod
    def from_dict(cls, dikt) -> 'RunStart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunStart of this RunStart.  # noqa: E501
        :rtype: RunStart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this RunStart.


        :return: The session_id of this RunStart.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this RunStart.


        :param session_id: The session_id of this RunStart.
        :type session_id: str
        """

        self._session_id = session_id
