app:
  name: smartem-decisions
  # There is technically no guarantee that every micrograph will be covered by at most 2 batches.
  # The size of the batches basically makes incredibly unlikely but there is nothing to guarantee it.
  particle_select_batch_size: 50000
rabbitmq:
  queue_name: default_queue
  routing_key: default_queue
