apiVersion: v1
kind: Secret
metadata:
  name: smartem-secrets
  namespace: smartem-decisions
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  RABBITMQ_USER: dXNlcm5hbWU=
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=
  GRAYLOG_PASSWORD_SECRET: c29tZXNlY3JldGZvcmdyYXlsb2c=
  GRAYLOG_ROOT_PASSWORD_SHA2: OGM4MjJkNzUyNjEwNzQxOTc3NTIyZGUzMDc4NzA1N2ZlMjEwMjUwMGVlMzY0ODExNDQ1M2M5MzkxMzc3NjA4Mw==
