"""add foil hole groups

Revision ID: c7bd4dcf5d02
Revises: b2c3d4e5f6a7
Create Date: 2026-03-27 11:57:51.350865

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7bd4dcf5d02"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currentqualitygroupprediction_grid_uuid"), table_name="currentqualitygroupprediction")
    op.drop_index(op.f("ix_currentqualitygroupprediction_group_uuid"), table_name="currentqualitygroupprediction")
    op.drop_constraint(
        op.f("currentqualitygroupprediction_metric_name_fkey"), "currentqualitygroupprediction", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("currentqualitygroupprediction_group_uuid_fkey"), "currentqualitygroupprediction", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("currentqualitygroupprediction_prediction_model_name_fkey"),
        "currentqualitygroupprediction",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("currentqualitygroupprediction_grid_uuid_fkey"), "currentqualitygroupprediction", type_="foreignkey"
    )
    op.create_foreign_key(None, "currentqualitygroupprediction", "foilholegroup", ["group_uuid"], ["uuid"])
    op.create_foreign_key(
        None, "currentqualitygroupprediction", "qualitypredictionmodel", ["prediction_model_name"], ["name"]
    )
    op.create_foreign_key(None, "currentqualitygroupprediction", "grid", ["grid_uuid"], ["uuid"])
    op.create_foreign_key(None, "currentqualitygroupprediction", "qualitymetric", ["metric_name"], ["name"])
    op.drop_index(op.f("ix_foilholegroup_grid_uuid"), table_name="foilholegroup")
    op.drop_constraint(op.f("foilholegroup_grid_uuid_fkey"), "foilholegroup", type_="foreignkey")
    op.create_foreign_key(None, "foilholegroup", "grid", ["grid_uuid"], ["uuid"])
    op.drop_constraint(
        op.f("foilholegroupmembership_foilhole_uuid_fkey"), "foilholegroupmembership", type_="foreignkey"
    )
    op.drop_constraint(op.f("foilholegroupmembership_group_uuid_fkey"), "foilholegroupmembership", type_="foreignkey")
    op.create_foreign_key(None, "foilholegroupmembership", "foilholegroup", ["group_uuid"], ["uuid"])
    op.create_foreign_key(None, "foilholegroupmembership", "foilhole", ["foilhole_uuid"], ["uuid"])
    op.drop_index(op.f("ix_qualitygroupprediction_group_uuid"), table_name="qualitygroupprediction")
    op.drop_constraint(
        op.f("qualitygroupprediction_prediction_model_name_fkey"), "qualitygroupprediction", type_="foreignkey"
    )
    op.drop_constraint(op.f("qualitygroupprediction_group_uuid_fkey"), "qualitygroupprediction", type_="foreignkey")
    op.drop_constraint(op.f("qualitygroupprediction_grid_uuid_fkey"), "qualitygroupprediction", type_="foreignkey")
    op.drop_constraint(op.f("qualitygroupprediction_metric_name_fkey"), "qualitygroupprediction", type_="foreignkey")
    op.create_foreign_key(None, "qualitygroupprediction", "qualitymetric", ["metric_name"], ["name"])
    op.create_foreign_key(None, "qualitygroupprediction", "qualitypredictionmodel", ["prediction_model_name"], ["name"])
    op.create_foreign_key(None, "qualitygroupprediction", "foilholegroup", ["group_uuid"], ["uuid"])
    op.create_foreign_key(None, "qualitygroupprediction", "grid", ["grid_uuid"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "qualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "qualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "qualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "qualitygroupprediction", type_="foreignkey")
    op.create_foreign_key(
        op.f("qualitygroupprediction_metric_name_fkey"),
        "qualitygroupprediction",
        "qualitymetric",
        ["metric_name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("qualitygroupprediction_grid_uuid_fkey"),
        "qualitygroupprediction",
        "grid",
        ["grid_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("qualitygroupprediction_group_uuid_fkey"),
        "qualitygroupprediction",
        "foilholegroup",
        ["group_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("qualitygroupprediction_prediction_model_name_fkey"),
        "qualitygroupprediction",
        "qualitypredictionmodel",
        ["prediction_model_name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_qualitygroupprediction_group_uuid"), "qualitygroupprediction", ["group_uuid"], unique=False
    )
    op.drop_constraint(None, "foilholegroupmembership", type_="foreignkey")
    op.drop_constraint(None, "foilholegroupmembership", type_="foreignkey")
    op.create_foreign_key(
        op.f("foilholegroupmembership_group_uuid_fkey"),
        "foilholegroupmembership",
        "foilholegroup",
        ["group_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("foilholegroupmembership_foilhole_uuid_fkey"),
        "foilholegroupmembership",
        "foilhole",
        ["foilhole_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "foilholegroup", type_="foreignkey")
    op.create_foreign_key(
        op.f("foilholegroup_grid_uuid_fkey"), "foilholegroup", "grid", ["grid_uuid"], ["uuid"], ondelete="CASCADE"
    )
    op.create_index(op.f("ix_foilholegroup_grid_uuid"), "foilholegroup", ["grid_uuid"], unique=False)
    op.drop_constraint(None, "currentqualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "currentqualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "currentqualitygroupprediction", type_="foreignkey")
    op.drop_constraint(None, "currentqualitygroupprediction", type_="foreignkey")
    op.create_foreign_key(
        op.f("currentqualitygroupprediction_grid_uuid_fkey"),
        "currentqualitygroupprediction",
        "grid",
        ["grid_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("currentqualitygroupprediction_prediction_model_name_fkey"),
        "currentqualitygroupprediction",
        "qualitypredictionmodel",
        ["prediction_model_name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("currentqualitygroupprediction_group_uuid_fkey"),
        "currentqualitygroupprediction",
        "foilholegroup",
        ["group_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("currentqualitygroupprediction_metric_name_fkey"),
        "currentqualitygroupprediction",
        "qualitymetric",
        ["metric_name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_currentqualitygroupprediction_group_uuid"),
        "currentqualitygroupprediction",
        ["group_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_currentqualitygroupprediction_grid_uuid"), "currentqualitygroupprediction", ["grid_uuid"], unique=False
    )
    # ### end Alembic commands ###
