# coding: utf-8

"""
    Decision Service API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from cryoem_client.api_client import ApiClient


class DecisionServiceConfigurationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_v1_configuration_delete(self, **kwargs):  # noqa: E501
        """Delete a registered decision service configuration.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_delete(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v1_configuration_delete_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v1_configuration_delete_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v1_configuration_delete_with_http_info(self, **kwargs):  # noqa: E501
        """Delete a registered decision service configuration.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_delete_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_configuration_delete" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/Configuration', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v1_configuration_get(self, **kwargs):  # noqa: E501
        """Get decision service configuration.  # noqa: E501

        Sample request:        ../Configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: DecisionServiceConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v1_configuration_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v1_configuration_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v1_configuration_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get decision service configuration.  # noqa: E501

        Sample request:        ../Configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: DecisionServiceConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_configuration_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/Configuration', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DecisionServiceConfiguration',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v1_configuration_plugin_patch(self, **kwargs):  # noqa: E501
        """Patch the existing smart plugin configuration  # noqa: E501

        Sample request:        PATCH      {                \"PluginName\": \"StageSettlingTimePrediction\",        \"CustomPluginSelection\": true      }    Sample response:        RESPONSE      {                \"PluginName\": \"StageSettlingTimePrediction\",        \"CustomPluginSelection\": true,        \"Timestamp\" : \"10/20/2022 14:38\"      }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_plugin_patch(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SmartPluginConfiguration body: Smart plugin configuration.
        :return: SmartPluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v1_configuration_plugin_patch_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v1_configuration_plugin_patch_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v1_configuration_plugin_patch_with_http_info(self, **kwargs):  # noqa: E501
        """Patch the existing smart plugin configuration  # noqa: E501

        Sample request:        PATCH      {                \"PluginName\": \"StageSettlingTimePrediction\",        \"CustomPluginSelection\": true      }    Sample response:        RESPONSE      {                \"PluginName\": \"StageSettlingTimePrediction\",        \"CustomPluginSelection\": true,        \"Timestamp\" : \"10/20/2022 14:38\"      }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_plugin_patch_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SmartPluginConfiguration body: Smart plugin configuration.
        :return: SmartPluginConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_configuration_plugin_patch" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/Configuration/Plugin', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SmartPluginConfiguration',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_v1_configuration_post(self, **kwargs):  # noqa: E501
        """Post new decision service configuration.  # noqa: E501

        Sample requests:                    POST      {          \"SmartPluginConfigurations\" : [              {                  \"PluginName\": \"StageSettlingTimePrediction\",                  \"CustomPluginSelection\": true              },              {                  \"PluginName\": \"SkipGridSquarePrediction\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"SmartFocusPrediction\",                  \"CustomPluginSelection\": true              },              {                  \"PluginName\": \"AutomaticFoilHoleSelection\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"AutomaticGridSquareSelection\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"IceThicknessFoilHolePrediction\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"AutomaticFoilHoleFinding\",                  \"CustomPluginSelection\": true              }          ]      }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DecisionServiceConfiguration body: Decision service configuration.
        :return: DecisionServiceConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_v1_configuration_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_v1_configuration_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_v1_configuration_post_with_http_info(self, **kwargs):  # noqa: E501
        """Post new decision service configuration.  # noqa: E501

        Sample requests:                    POST      {          \"SmartPluginConfigurations\" : [              {                  \"PluginName\": \"StageSettlingTimePrediction\",                  \"CustomPluginSelection\": true              },              {                  \"PluginName\": \"SkipGridSquarePrediction\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"SmartFocusPrediction\",                  \"CustomPluginSelection\": true              },              {                  \"PluginName\": \"AutomaticFoilHoleSelection\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"AutomaticGridSquareSelection\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"IceThicknessFoilHolePrediction\",                  \"CustomPluginSelection\": false              },              {                  \"PluginName\": \"AutomaticFoilHoleFinding\",                  \"CustomPluginSelection\": true              }          ]      }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_v1_configuration_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DecisionServiceConfiguration body: Decision service configuration.
        :return: DecisionServiceConfiguration
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_v1_configuration_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/Configuration', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DecisionServiceConfiguration',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
