apiVersion: v1
kind: ConfigMap
metadata:
  name: smartem-config
  namespace: smartem-decisions-production
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "smartem_db"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  HTTP_API_PORT: "8000"
  ADMINER_PORT: "8080"
