on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker local cache
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          # Need load and tags so we can test it below
          load: true
          tags: tag_for_testing

#      - name: Test container roles and functionality
#        run: |
#          echo "Testing smartem_decisions module import..."
#          docker run --rm tag_for_testing "python -c 'import smartem_decisions; print(\"Module imported successfully\")'"
#
#          echo "Testing CLI entry point..."
#          docker run --rm tag_for_testing "python -m smartem_decisions --version"
#
#          echo "Testing API role configuration..."
#          docker run --rm -e ROLE=api tag_for_testing "python -c 'import os; print(f\"Role: {os.environ.get(\"ROLE\", \"not set\")}\")"
#
#          echo "Testing worker role configuration..."
#          docker run --rm -e ROLE=worker tag_for_testing "python -c 'import os; print(f\"Role: {os.environ.get(\"ROLE\", \"not set\")}\")"
#
#          echo "Testing container can handle role-based startup (dry run)..."
#          docker run --rm -e ROLE=api tag_for_testing "python -c 'print(\"API role ready\")'"
#          docker run --rm -e ROLE=worker tag_for_testing "python -c 'print(\"Worker role ready\")'"

      - name: Create tags for publishing image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Push cached image to container registry
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        # This does not build the image again, it will find the image in the
        # Docker cache and publish it
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
