on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}

      - name: Build and export to Docker local cache
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          load: true
          tags: tag_for_testing

      - name: Create tags for publishing image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gcr.io/diamond-pubreg/smartem_decisions/smartem_decisions
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Push cached image to GCR
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
