name: Build EPU Data Intake binary for Windows

on:
  push:
    branches: [ main ]
    paths:
      - 'src/epu_data_intake/**'
      - '.github/workflows/build-win-epu-data-intake.yml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Build from branch'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build parser util with PyInstaller
      run: >-
        pyinstaller --onefile
        --name smartem_epu_data_intake_parser
        src/epu_data_intake/fs_parser.py

    - name: Build watcher util with PyInstaller
      run: >-
        pyinstaller --onefile
        --name smartem_data_intake_watcher
        src/epu_data_intake/fs_watcher.py

    - name: Copy README to dist directory
      run: |
        copy src/epu_data_intake/README.md dist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: epu-data-intake-tools-v${{ github.run_number }}-${{ github.sha }}
        path: dist/
