name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  pull_request:
    branches:
      - main
    types:
      - opened        # When PR is first created
      - synchronize   # When new commits are pushed to PR
      - ready_for_review  # When a draft PR is marked as ready
      # - edited      # When PR title/description is edited (DISABLED to avoid unnecessary runs)
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'  # Skip when only issue templates change
      - '.github/PULL_REQUEST_TEMPLATE/**'  # Skip when only PR templates change

jobs:
  check:
    # Skip job if PR title starts with [WIP] but still run for non-PR events
    if: ${{ !startsWith(github.event.pull_request.title, '[WIP]') || github.event_name != 'pull_request' }}
    uses: ./.github/workflows/_check.yml

# TODO restore
#  lint:
#    needs: check
#    if: needs.check.outputs.branch-pr == ''
#    uses: ./.github/workflows/_tox.yml
#    with:
#      tox: pre-commit,type-checking

  test:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    strategy:
      matrix:
        runs-on: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python-version: ["3.12"]
        include:
          # Include one that runs in the dev environment
          - runs-on: "ubuntu-latest"
            python-version: "dev"
      fail-fast: true
    uses: ./.github/workflows/_test.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      python-version: ${{ matrix.python-version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  container:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_container.yml
    permissions:
      contents: read
      packages: write

  docs:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_docs.yml

  dist:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_dist.yml

# TODO restore or remove
#  release:
#    if: github.ref_type == 'tag'
#    needs: [dist, docs]
#    uses: ./.github/workflows/_release.yml
#    permissions:
#      contents: write
