name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/_docs.yml'
      - '.github/workflows/docs-only.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/_docs.yml'
      - '.github/workflows/docs-only.yml'

jobs:
  docs:
    uses: ./.github/workflows/_docs.yml
